-- Generated by nwg-displays on 2026-06-21 at 16:55:07. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "3640x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@74.97",
    position = "0x0",
    scale = 1.0,
    transform = 3
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "1080x480",
    scale = 1.0
})
